---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/5/8 18:29
---

print("================ 数组访问 userdata ================")
a = array.new(1000)

a[10] = true

print("a[10]", a[10])
print("#a", #a)