---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/5/1 21:40
---

local mylib = require "mylib"
t = mylib.dir('/Users/jiangpengyong/Desktop/code/CPP/CPP2022/lua/lua调用c');
for key, value in pairs(t) do
    io.write(key, value, "\n")
end