---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/5/8 16:16
---

local a = Counter.newCounter()
local b = Counter.newCounter()

print("a", a(), a(), a())
print("b", b())