---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2023/11/5 23:11
---

local result = split("江_澎_涌", "_");

print("length", #result);

for i, v in ipairs(result) do
    print(i, " --- ", v)
end
