---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2023/10/23 08:37
---

print("dir: ", dir);

local currentPath = debug.getinfo(1, "S").source:sub(2):match("(.*/)")

print("--------------- 存在目录 ---------------")
t = dir(currentPath)
for key, value in pairs(t) do
    io.write(key, value, "\n")
end
print("------------------------------")

print("--------------- 不存在目录 ---------------")
t1, t2 = dir(currentPath .. '不存在的目录')
print(t1, t2)
print("------------------------------")