---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2023/10/23 08:37
---

print("dir: ", dir);

local currentPath = debug.getinfo(1, "S").source:sub(2):match("(.*/)")

print("--------------- 传递错误参数 ---------------")
print(pcall(function()
    dir({ "传递错误参数" })
end))

print("--------------- 存在目录 ---------------")
local dirTable
local isSuccess, msg = pcall(function()
    dirTable = dir(currentPath)
end)
if isSuccess then
    for key, value in pairs(dirTable) do
        io.write(key, value, "\n")
    end
else
    print("打开目录失败", currentPath, msg)
end

print("------------------------------")

print("--------------- 不存在目录 ---------------")
isSuccess, msg = pcall(function()
    dirTable = dir("不存在目录")
end)
if isSuccess then
    for key, value in pairs(dirTable) do
        io.write(key, value, "\n")
    end
else
    print("打开目录失败", currentPath, msg)
end
print("------------------------------")