---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2023/10/23 08:37
---

print("dir: ", dir, "\n");

print("--------------- 存在目录 ---------------\n")
t = dir('/Users/jiangpengyong/Desktop/code/Lua/Lua_CPP_2022/6、Lua回调C++')
for key, value in pairs(t) do
    io.write(key, value, "\n")
end
print("------------------------------\n")

print("--------------- 不存在目录 ---------------\n")
t1, t2 = dir('/Users/jiangpengyong/Desktop/code/Lua/Lua_CPP_2022/3、lua调用c1')
print(t1, t2, "\n")
print("------------------------------\n")