---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/5/8 18:29
---

a = array.new(1000)
--for i = 1, 1000 do
--    array.set(a, i, i % 2 == 0)
--end

array.set(a, 12, true);
array.set(a, 11, true);

print(array.get(a, 10))
print(array.get(a, 11))
print(array.size(a))