---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/5/1 20:22
---

co = coroutine.wrap(function()
    print("江澎涌5")
    print(pcall(coroutine.yield))
    print("江澎涌3")
end)

print("江澎涌1")

co()

print("江澎涌2")

co()