---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/5/8 18:29
---

local a = array.new(1000)
print("type(a) =>>", type(a))

array.set(a, 12, true);
array.set(a, 11, true);

print("第 10 个元素：", array.get(a, 10))
print("第 11 个元素：", array.get(a, 11))
print("长度：", array.size(a))

array.set(a, 11, false);
print("第 11 个元素：", array.get(a, 11))