---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/5/8 12:05
---

x, name = tuple.new(10, "hi", {}, 3)
print(x, name)
print(x(1))
print(x(2))
print(x())

x1 = tuple.new("jiang", {})
print(x1())