---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/5/8 18:29
---

local myUser = user.new("江澎涌", 29)

print(pcall(function()
    print(user.introduce(io.stdio))
end))

print(user.introduce(myUser))