---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/5/8 18:29
---

a = array.new(1000)
print("type(a) =>>", type(a))
--for i = 1, 1000 do
--    array.set(a, i, i % 2 == 0)
--end

array.set(a, 12, true);
array.set(a, 11, true);

print("第 10 个元素：", array.get(a, 10))
print("第 11 个元素：", array.get(a, 11))
print("长度：", array.size(a))

array.set(a, 11, false);
print("第 11 个元素：", array.get(a, 11))

do
    print("================ 设置元表 ================")
    -- lua 可以设置元表中的属性，但不能更改元表
    print("设置前 array 元表", getmetatable(array.new(1)))
    -- 这里的设置元表是无效的
    local temptable = {}
    setmetatable(array, temptable)
    local metatable = getmetatable(array.new(1))
    print("设置后 array 元表", metatable, temptable)
    metatable.__index = metatable
    metatable.set = array.set
    metatable.get = array.get
    metatable.size = array.size

    local a = array.new(10)
    a:set(2, true)
    print("a:get(1)", a:get(1))
    print("a:get(2)", a:get(2))
    print("a:size()", a:size())
end