---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/5/8 18:29
---

print("================ 面向对象使用 userdata ================")
a = array.new(5)

a:set(1, false)
a:set(5, true)

print("第 5 个元素：", a:get(5))
print("第 1 个元素：", a:get(1))
print("长度：", a:size())
print("string：", a)

a:set(1, true);
a:set(5, false);
print("第 5 个元素：", a:get(5))
print("第 1 个元素：", a:get(1))
