---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2023/9/10 15:53
---

require("string")

local name, age = ...
local content = string.format("name: %s, age: %d", name, age)
print("Lua 脚本中打印", content)

local error = noneInitTable.name

local errorTable = {}
setmetatable(errorTable, {
    __tostring = function(table)
        return "Error table..."
    end
})
error(errorTable)

return content